services:
  splunk:
    image: splunk/splunk:latest
    hostname: splunk-standalone
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=what_lies_below
      - SPLUNK_GENERAL_TERMS=--accept-sgt-current-at-splunk-com
    ports:
      - "8000:8000" # Splunk Web UI
      - "8089:8089" # HTTP Event Collector (HEC)
    volumes:
      - splunk_data:/opt/splunk/var
volumes:
  splunk_data:
